### ISSUE TITLE
OpenMP tasking implementation using UPIR and LLVM OpenMP runtime

### ISSUE THREAD

**Issue by yanyh15** [passlab/rexompiler#105]
- Early work using OpenMP runtime kmp call for tasking: https://github.com/passlab/rexruntime/blob/master/rex/runtime/rex_kmp.cpp
- Patrick work of migrating Tapir to OpenMP LLVM runtime https://github.com/patrickf2000/kitsune/blob/openmp2/llvm/lib/Transforms/Tapir/OpenMPABI.cpp
- REX OpenMP task lowering: https://github.com/passlab/rexompiler/blob/main/src/midend/programTransformation/ompLowering/omp_lowering.cpp#L4543
- Off develop branch
- Ref: OpenMP CLang/LLVM support: https://github.com/llvm/llvm-project/blob/main/clang/lib/CodeGen/CGOpenMPRuntime.cpp

**Comment by yanyh15** [comment]
@patrickf2000 fixed the outlined function issue such that now in the nested parallel/task region, the outlined function for both parallel region and task region are now moved to a file separately, leveraging how anjia did for parallel and target

also move the task lowering function to a separate file.

**Comment by ouankou** [comment]
# Failed test:

### Source

```c
#include <stdio.h>

int main(int argc, char *argv[]) {
#pragma omp parallel
  {
#pragma omp single
    {
      printf("A ");
#pragma omp task
      { printf("race "); }
#pragma omp task
      { printf("car "); }
      printf("is fun to watch ");
    }
  } // End of parallel region
  printf("\n");
  return (0);
}
```

### Output

```bash
$ rose-compiler -rose:openmp:lowering -rose:skipfinalCompileStep task.c

Start parsing...
Start parsing...
Start parsing...
Start parsing...
ompparser directive is ready.
ompparser directive is ready.
ompparser directive is ready.
ompparser directive is ready.
func                            = 0x7f56cd2f8e78 
func->get_definingDeclaration() = 0x7f56cd2f8e78 
func                            = 0x7f56cd2f8e78 
Segmentation fault (core dumped)
```

### GDB output
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Start parsing...
Start parsing...
Start parsing...
Start parsing...
ompparser directive is ready.
ompparser directive is ready.
ompparser directive is ready.
ompparser directive is ready.
func                            = 0x7fffebeb8e78 
func->get_definingDeclaration() = 0x7fffebeb8e78 
func                            = 0x7fffebeb8e78 

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff70b5a23 in void std::vector<SgDeclarationStatement*, std::allocator<SgDeclarationStatement*> >::emplace_back<SgDeclarationStatement*>(SgDeclarationStatement*&&) ()
   from /home/ouankou/Projects/rexdev/rex_install/lib/librose.so.0
(gdb) bt
#0  0x00007ffff70b5a23 in void std::vector<SgDeclarationStatement*, std::allocator<SgDeclarationStatement*> >::emplace_back<SgDeclarationStatement*>(SgDeclarationStatement*&&) ()
   from /home/ouankou/Projects/rexdev/rex_install/lib/librose.so.0
#1  0x00007ffff70b4835 in OmpSupport::transOmpTask(SgNode*) () from /home/ouankou/Projects/rexdev/rex_install/lib/librose.so.0
#2  0x00007ffff70acd42 in OmpSupport::lower_omp(SgSourceFile*) () from /home/ouankou/Projects/rexdev/rex_install/lib/librose.so.0
#3  0x00007ffff5928706 in SgFile::secondaryPassOverSourceFile() () from /home/ouankou/Projects/rexdev/rex_install/lib/librose.so.0
#4  0x00007ffff592d329 in SgProject::parse() () from /home/ouankou/Projects/rexdev/rex_install/lib/librose.so.0
#5  0x00007ffff592ed6f in SgProject::parse(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) () from /home/ouankou/Projects/rexdev/rex_install/lib/librose.so.0
#6  0x00007ffff5a91bb5 in SgProject::SgProject(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) () from /home/ouankou/Projects/rexdev/rex_install/lib/librose.so.0
#7  0x00007ffff7219cd6 in frontend(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) () from /home/ouankou/Projects/rexdev/rex_install/lib/librose.so.0
#8  0x000055555555ca4f in main ()
```

According to the GDB output, the function `transOmpTask(SgNode*)` in `omp_task.cpp` caused the problem. I had a quick scan of the code but didn't check many details. It seems a list of outlined functions is used to help the transformation. However, we have dropped this approach on the CPU side (and will do the same thing to GPU offloading soon). That vector variable does not exist in `omp_lowering.cpp` anymore.
Currently, we use top-down breadth-first traversal to lower OpenMP directives, which is opposite to the original bottom-up post-order traversal in ROSE.

For example, given the following code:
```c
#pragma omp parallel
{
#pragma omp for
#pragma omp simd
  for (int i = 0; i < 16; i++)
    ...
}.
```

REX will 1) outline the parallel region first and remove the parallel directive, 2) transform the for directive that has been moved to the outlined function, and then 3) transform the simd directive in the lowered loop.
